//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppComponents.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Received.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Bytes_Received {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Bytes_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Sent.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Bytes_Sent {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Bytes_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Requests.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Completed_Requests {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Completed_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected Requests.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Disconnected_Requests {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Disconnected_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Error Rate.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Error_Rate {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Error_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Failures.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Logon_Failures {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Logon_Failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Successes.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Logon_Successes {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Logon_Successes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Requests.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Queued_Requests {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Queued_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Requests.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Rejected_Requests {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Rejected_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Execution Time.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Request_Execution_Time {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Request_Execution_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests in Execution.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Requests_in_Execution {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Requests_in_Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Out Requests.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Timed_Out_Requests {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Timed_Out_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Errors.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Unhandled_Errors {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Unhandled_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Performance.
        /// </summary>
        internal static string StdPerfCounters_LoadASPPerfCounters_Web_Performance {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadASPPerfCounters_Web_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Performance.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Application_Performance {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Application_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Memory.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Available_Memory {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Available_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_CPU_Usage {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_CPU_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions Thrown / sec.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Errors___sec {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Errors___sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks and Thread Contention.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Locks_and_Thread_Contention {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Locks_and_Thread_Contention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Cleanup Time %.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Memory_Cleanup_Time__ {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Memory_Cleanup_Time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Memory_Usage {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Memory_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connections.
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_Network_Connections {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_Network_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Uptime (seconds).
        /// </summary>
        internal static string StdPerfCounters_LoadCLRPerfCounters_System_Uptime__seconds_ {
            get {
                return ResourceManager.GetString("StdPerfCounters_LoadCLRPerfCounters_System_Uptime__seconds_", resourceCulture);
            }
        }
    }
}
