//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppComponents.AssResource", typeof(AssResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_email_uses_ssl {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_email_uses_ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RavenDB database url.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_RavenDB_database_url {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_RavenDB_database_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/setdatapath.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_set_distributed_file_path {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_set_distributed_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email account name.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_set_email_account_name {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_set_email_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email account password.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_set_email_account_password {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_set_email_account_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_set_email_port {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_set_email_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set email server.
        /// </summary>
        internal static string RavenGlobalConfig_MaybeInitDefaults_set_email_server {
            get {
                return ResourceManager.GetString("RavenGlobalConfig_MaybeInitDefaults_set_email_server", resourceCulture);
            }
        }
    }
}
