///////////////////////////////////////////////////////////
//  BitTorrentInfo.cs
//  Implementation of the Class BitTorrentInfo
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2012 14:41:49
///////////////////////////////////////////////////////////

namespace Lok.Unik.ModelCommon.Client
{
    using Lok.Unik.ModelCommon.Interfaces;

    public class BitTorrentInfo : FileTransferInfo
    {
        public BitTorrentInfo()
        {
        }

        public byte[] Torrent { get; set; }
    }

    //end BitTorrentInfo
}

//end namespace System