///////////////////////////////////////////////////////////
//  Kiosk.cs
//  Implementation of the Class Kiosk
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2012 14:41:50
///////////////////////////////////////////////////////////

using Lok.Unik.ModelCommon.Events;

namespace Lok.Unik.ModelCommon.Client
{
    using System;
    using System.Collections.Generic;

    using Lok.Unik.ModelCommon.Command;
    using Lok.Unik.ModelCommon.Info;
    using Lok.Unik.ModelCommon.Interfaces;

    public class Kiosk : Device
    {
        public override IList<Tag> Tags { get; set; }

        public Kiosk()
        {
            Type = DeviceType.Kiosk;
            LastContactTimeUTC = DateTime.MinValue;
            LastStatusChangeUTC = DateTime.MinValue;
        }
       
        public string LocationAtStore { get; set; }

        public DateTime LastStatusChangeUTC { get; set; }

        public DateTime LastContactTimeUTC { get; set; }


    }

    //end Kiosk
}

//end namespace System