///////////////////////////////////////////////////////////
//  IApplication.cs
//  Implementation of the Interface IApplication
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2012 14:41:50
///////////////////////////////////////////////////////////

namespace Lok.Unik.ModelCommon.Interfaces
{
    using System;
    using System.Collections.Generic;

    using Lok.Unik.ModelCommon.Client;

    
    public interface IApplication : ITaggableEntity
    {
        //Guid Id { get; set; }
        string Name { get; set; }
        BitTorrentInfo TransferInfo { get; set; }
        
        string Version { get; set; }
        string ManagedAppController { get; set; }
        string ControllerArgs { get; set; }
        string InstallationPath { get; set; }
        string RelativeConfigPath { get; set; }
        string RelativeExePath { get; set; }
        string AdditionalArgs { get; set; }
        double DeploymentFileSize { get; set; }
        string ContentIndex { get; set; }
    }


    public enum ManagedAppControllerKeys
    {
        LoKMediaEngineXCopyManagedApps,
        LoKMediaEngineInstManagedApps,
        UninstrumentedInstManagedApps
    }

    

    //end IApplication
}

//end namespace System