///////////////////////////////////////////////////////////
//  IFileTransferInfo.cs
//  Implementation of the Interface IFileTransferInfo
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2012 14:41:50
///////////////////////////////////////////////////////////




namespace Lok.Unik.ModelCommon.Interfaces {
    using System;

    public interface IFileTransferInfo {
        Uri FileTransferUri { get; set; }

        string ServerFile { get; set; }
	}//end IFileTransferInfo

}//end namespace System