///////////////////////////////////////////////////////////
//  ITaggableEntity.cs
//  Implementation of the Interface ITaggableEntity
//  Generated by Enterprise Architect
//  Created on:      14-Sep-2012 14:41:50
///////////////////////////////////////////////////////////

namespace Lok.Unik.ModelCommon.Interfaces {
    using System;
    using System.Collections.Generic;

    using Lok.Unik.ModelCommon.Client;

    using Raven.Imports.Newtonsoft.Json;

    public interface ITaggableEntity {

        [JsonProperty(PropertyName = "tags")]
        IList<Tag> Tags
        {
            get;
            set;
        }

        //Must be a guid
        Guid Id
        {
            get;
            set;
        }

    }//end ITaggableEntity

}//end namespace System